<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rover_arm">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    
    <!-- Link lengths -->
    <xacro:property name="base_height" value="0.1364"/>
    <xacro:property name="link1_length" value="0.1752"/>
    <xacro:property name="link2_length" value="0.1608"/>
    <xacro:property name="link3_length" value="0.2182"/>
    
    <!-- Masses -->
    <xacro:property name="base_mass" value="0.650"/>
    <xacro:property name="link1_mass" value="0.220"/>
    <xacro:property name="link2_mass" value="0.200"/>
    <xacro:property name="link3_mass" value="0.250"/>
    <xacro:property name="end_effector_mass" value="0.140"/>

    <!-- Materials -->
    <material name="black">
        <color rgba="0.1 0.1 0.1 1"/>
    </material>

    <!-- Base Link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <!-- <geometry>
                <cylinder radius="0.05" length="${base_height}"/>
            </geometry> -->
            <geometry>
                <mesh filename="file://$(find install)/rover_arm_description/share/rover_arm_description/urdf/obj/base.stl" scale="1 1 1"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="${base_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <mass value="${base_mass}"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <!-- Joint 1: Base rotation -->
    <joint name="joint1" type="revolute">
        <parent link="base_link"/>
        <child link="link1"/>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-PI}" upper="${PI}" effort="100" velocity="1.0"/>
    </joint>

    <!-- Link 1 -->
    <link name="link1">
        <visual>
            <origin xyz="${link1_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${link1_length} 0.05 0.05"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="${link1_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${link1_length} 0.05 0.05"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${link1_length/2} 0 0" rpy="0 0 0"/>
            <mass value="${link1_mass}"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <!-- Joint 2 -->
    <joint name="joint2" type="revolute">
        <parent link="link1"/>
        <child link="link2"/>
        <origin xyz="${link1_length} 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-PI/2}" upper="${PI/2}" effort="100" velocity="1.0"/>
    </joint>

    <!-- Link 2 -->
    <link name="link2">
        <visual>
            <origin xyz="${link2_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${link2_length} 0.05 0.05"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="${link2_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${link2_length} 0.05 0.05"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${link2_length/2} 0 0" rpy="0 0 0"/>
            <mass value="${link2_mass}"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <!-- Joint 3 -->
    <joint name="joint3" type="revolute">
        <parent link="link2"/>
        <child link="link3"/>
        <origin xyz="${link2_length} 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-PI/2}" upper="${PI/2}" effort="100" velocity="1.0"/>
    </joint>

    <!-- Link 3 -->
    <link name="link3">
        <visual>
            <origin xyz="${link3_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${link3_length} 0.05 0.05"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="${link3_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${link3_length} 0.05 0.05"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${link3_length/2} 0 0" rpy="0 0 0"/>
            <mass value="${link3_mass}"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <!-- End effector frame -->
    <link name="end_effector">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${end_effector_mass}"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="end_effector_joint" type="fixed">
        <parent link="link3"/>
        <child link="end_effector"/>
        <origin xyz="${link3_length} 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Gazebo required transmission elements -->
    <transmission name="joint1_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint1">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint1_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="joint2_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint2">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint2_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="joint3_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint3">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint3_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

</robot> 