# Default initial positions for my_robot_arm's ros2_control fake system

initial_positions:
  end_effector_rotation: 0
  joint2: 0
  joint3: 0
  joint4: 0
  joint5: 0
  left_finger_joint: 0
  right_finger_joint: 0