# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - panda_arm_controller
    - hand_controller

  panda_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint2
      - joint3
      - joint4
      - joint5
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - end_effector_rotation
      - left_finger_joint
      - right_finger_joint
    action_ns: gripper_cmd
    default: true